[default]
bootstrap.servers=pkc-619z3.us-east1.gcp.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username=GTM2K6GBGKW5QMYC
sasl.password=cfltw5fvU84vcbx9QsMPlozRqFepG/p+l/DMWJPmBGmcj/Cpn92/Z0iaGLLHxSvw

[consumer]
group.id=python_kafka101_group_1
# 'auto.offset.reset=earliest' to start reading from the beginning of
# the topic if no committed offsets exist.
auto.offset.reset=earliest